name: Deploy Coupon API to QA environment

on:
  push:
    branches:
      - staging

env:
  AZURE_WEBAPP_NAME: arkx-qa-api-coupon
  AZURE_RG: ArkxUberQa
  IMAGE_NAME: arkx-qa-api-coupon

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      run: echo ${{ secrets.REGISTRY_PASSWORD_QA }} | docker login ${{ secrets.REGISTRY_LOGIN_SERVER_QA }} -u ${{ secrets.REGISTRY_USERNAME_QA }} --password-stdin

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER_QA }}/${{ env.IMAGE_NAME }}:latest

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_QA }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.REGISTRY_LOGIN_SERVER_QA }}/${{ env.IMAGE_NAME }}:latest
        
    - name: Azure logout
      run: |
        az logout
